### ISSUE TITLE
gmodula.lua error: split(2) cannot split 8 outputs stack traceback

### ISSUE THREAD

**Issue by lxltaibo** [Fang-Haoshu/multi-human-pose#3]
Here is the error when I train the model using 『th main.lua -expID test -loadModel xx.t7 -addDPG -addSTN -addParallelSPPE 』
![default](https://cloud.githubusercontent.com/assets/22167267/25112590/d38714a0-2424-11e7-99a1-875dad397ec0.png)

**Comment by Fang-Haoshu** [comment]
Do you use the link https://pan.baidu.com/s/1hsft2YC to download the model?

**Comment by lxltaibo** [comment]
yes, first i use  umich-stacked-hourglass.t7 pretrain model using DPG, then using addParallelSPPE, addSTN, addDPG with the final_model.t7

**Comment by Fang-Haoshu** [comment]
When does this error occur? During training or testing?

**Comment by lxltaibo** [comment]
Training, (training is ok with the cmd 'th main.lua -expID test1 -addDPG' , this error occurs when training with the cmd 'th mian.lua -expID test2 -addDPG -addSTN -addParallelSPPE')

**Comment by Fang-Haoshu** [comment]
Does is happen when running
 th main.lua -expID finetune -addDPG?

**Comment by lxltaibo** [comment]
Training is ok just using -addDPG

**Comment by Fang-Haoshu** [comment]
You are trying to use a 8-stacked hourglass network. But the code is written for a 2-stacked one. I remember that the model I provided in https://pan.baidu.com/s/1hsft2YC is a 2-stacked one. Do you use the model from there? If yes, I will need to have a check.

BTW, I will update the code for 8-stacked one recently.

**Comment by lxltaibo** [comment]
That might be it, I probably use the 8-stacked hourglass from https://github.com/anewell/pose-hg-train, i will check it and tell you the result.
Thanks

**Comment by lxltaibo** [comment]
You're right, the training is ok when using the pretrain model with 2 stacked hourglass.

Thank you very much!

**Comment by Fang-Haoshu** [comment]
Happy to hear that:)
