### ISSUE TITLE
Some questions about the training

### ISSUE THREAD

**Issue by lxltaibo** [Fang-Haoshu/multi-human-pose#4]
Q1(using rmpe v1): The training time is 1s725ms without using anything (like DPG, SSTN) you added, 3s849ms with addDPG,  5s168ms using addDPG,  addSSTN and addParallelSPPE. I think the time is a bit long because the training time is 72ms when using the Newell code(batchsize = 4, nStack = 3); I want to know  if your training time like mine;

Q2(using rmpe v2): What's the ‘mu’ and 'std' mean in the ./train/data/mpii-box/?

My training environment: Titan X (pascal).

Many thanks!

**Comment by Fang-Haoshu** [comment]
v1 is the old version. Newell also updated his code before. Now the v2 is based on the current version of Newell's code and is much faster.
We have updated our arxiv paper. For the meaning of  ‘mu’ and 'std' you can check the paper and refer to the PGPG part

**Comment by lxltaibo** [comment]
Thx！！！
